SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME 
FROM ANIMAL_OUTS AS O INNER JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND (O.SEX_UPON_OUTCOME LIKE 'Neutered Male' OR O.SEX_UPON_OUTCOME LIKE 'Spayed Female')
ORDER BY ANIMAL_ID