SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS AS O
INNER JOIN ANIMAL_INS AS I
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME

-- 입양일 (O.DATETIME) 이 보호시작일 (I.DATETIME) 보다 빠른 조건
-- 날짜가 빠르다 == 값이 더 작다는 의미