-- SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (O.AMOUNT * P.PRICE) AS TOTAL_SALES FROM FOOD_PRODUCT AS P, FOOD_ORDER AS O
-- WHERE P.PRODUCT_ID = O.PRODUCT_ID AND O.PRODUCE_DATE LIKE '%2022-05%'
-- ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (SUM(O.AMOUNT * P.PRICE)) AS TOTAL_SALES FROM FOOD_PRODUCT AS P, FOOD_ORDER AS O
WHERE P.PRODUCT_ID = O.PRODUCT_ID AND O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;

-- 같은 제품에 대한 주문들의 매출은 모두 합해야 하므로 group by 이용